### ISSUE TITLE
Kanban Board Setup - Microverse Final Capstone

### ISSUE THREAD

**Issue by RaoAkif** [RaoAkif/RentACar-Frontend#28]
## Repositories
[Frontend Repo](https://github.com/RaoAkif/RentACar-Frontend)
[Backend Repo](https://github.com/RaoAkif/RentACar-Backend)

## Team
Our team consists of:
[Andres](https://github.com/andres-condezo)
[Retky](https://github.com/Retky)
[Fernando](https://github.com/fasaldana)
[RaoAkif](https://github.com/RaoAkif)

![image](https://user-images.githubusercontent.com/61361037/184034736-8a40837c-5733-4689-93e5-68d8283013f5.png)

**Comment by MuriloRoque** [comment]
Hi @RaoAkif, @fasaldana, @andres-condezo, @Retky,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
